import TitleTextSection from "@/components/TitleTextSection";
import Title from "@/components/Title";
import Image from "next/image";
import aboutIllustration from "@/../public/images/about-illustration.jpg";
import logoDark from "@/../public/images/logo-dark.svg";
import { log } from "console";

export default function AboutPage() {
  return (
    <main className="min-h-full flex flex-col items-center p-8 space-y-8">
      <Title title="Mon parcours" />
      <div className="relative">
        <Image
          className="rounded-xl"
          src={aboutIllustration}
          alt="illustration. a guy walking with his backpack"
        />
        <Image
          className="absolute bottom-1 left-1 w-6 h-6"
          src={logoDark}
          alt="logo with AS caps letters"
        />
        <span className="absolute bottom-1 left-9 text-secondary text-xs font-light">
          Generated by A.I
        </span>
      </div>
      <p className="text-base text-justify font-medium text-secondary">
        J’ai grandi en Normandie, plus particulièrement près de la ville de
        Rouen. J’y ai fait mes études en commençant par un baccalauréat
        technique (sciences et technologies de l’industrie et du développement
        durable). Je me suis ensuite orienté vers le commerce avec un BTS
        management des unités commerciales. J’ai poursuivi dans le secteur de
        l’automobile par passion, mais je n’y ai pas trouvé mon bonheur. En
        parallèle, je me suis intéressé au web marketing et j’ai pu entamer une
        activité d’indépendant dans ce secteur. Cette porte m’a ouvert tout un
        univers sur le développement, et le web tout particulièrement. J’ai
        commencé en autodidacte par construire des sites no-code grâce à Shopify
        ou Wordpress, puis j’ai voulu rentrer dans la technique, j’ai suivi la
        formation de l’école O’clock en 2023. Je continu d’approfondir les
        technologies qui me tiennent à coeur en cherchant une opportunité pour
        mettre en pratique mes compétences pour cette année 2024.
      </p>
    </main>
  );
}
